/**
 * Author:     Crazy Broke Asians
 * Date:       Dec-08-2023
 * Course:     CS 3505, University of Utah
 * Assignment: A9: An Educational App
 * File Contents
 *      It contains all necessary information needed to form a quiz popup.
*/

#ifndef QUIZ_H
#define QUIZ_H

#include <QWidget>
#include <QMap>
#include <QList>
#include <Box2D/Box2D.h>
#include <QTimer>
#include <QPainter>
#include <QLabel>
#include <QPushButton>

namespace Ui {
class Quiz;
}

class Quiz : public QWidget
{
    Q_OBJECT
    QLabel *backgroundLabel;

public:
    ///
    /// \brief Quiz
    ///     Constructor.
    /// \param parent - The parent widget.
    ///
    explicit Quiz(QWidget *parent = nullptr);

    ///
    /// \brief Destructor
    ///
    ~Quiz();

    ///
    /// \brief showRandomQuestion
    /// Displays a randomly selected question from the question bank.
    ///
    void showRandomQuestion();

    ///
    /// \brief resetButtons
    /// Resets the state of buttons.
    ///
    void resetButtons();

    ///
    /// \brief closeWindow
    /// Closes the current window or dialog.
    ///
    void closeWindow();

    ///
    /// \brief setValues
    ///     Sets the initial values for the question bank and list of questions.
    /// \param questionBank - A QMap representing the question bank with categories as keys and corresponding lists of questions.
    /// \param questions - A QList containing the questions to be used in the quiz.
    ///
    void setValues(QMap<QString, QList<QString>> &questionBank, QList<QString> &questions);

    ///
    /// \brief setRandomOptions
    ///     Randomizes the order of options by shuffling the provided list of numbers.
    /// \param numbers - A QList of integers representing option indices.
    ///
    void setRandomOptions(QList<int> &numbers);

    ///
    /// \brief setBgImage
    ///     This checks the status of the tour and sets a background image for this quiz window.
    /// \param country - Status of the current country.
    ///
    void setBgImage(QString country);

signals:
    ///
    /// \brief randomizeOption
    /// Randomizes the order of answer options for the current question.
    ///
    void randomizeOption();

private slots:
    /*
     * Button clicked slots are auto-generated by Qt, which makes the code-style looking different.
     */

    ///
    /// \brief on_option1Button_clicked
    /// Slot function triggered when the first option button is clicked.
    ///
    void on_option1Button_clicked();

    ///
    /// \brief on_option2Button_clicked
    /// Slot function triggered when the second option button is clicked.
    ///
    void on_option2Button_clicked();

    ///
    /// \brief on_option3Button_clicked
    /// Slot function triggered when the third option button is clicked.
    ///
    void on_option3Button_clicked();

    ///
    /// \brief on_option4Button_clicked
    /// Slot function triggered when the fourth option button is clicked.
    ///
    void on_option4Button_clicked();

    ///
    /// \brief on_nextButton_clicked
    /// Slot function triggered when the "Next" button is clicked.
    ///
    void on_nextButton_clicked();

    ///
    /// \brief closeEvent
    /// Overridden method called when the window close event occurs.
    /// \param bar - A QCloseEvent parameter representing the close event.
    ///
    void closeEvent(QCloseEvent *bar);

    ///
    /// \brief closePaint
    /// Closes the paint-related functionality or window.
    ///
    void closePaint();

protected:
    ///
    /// \brief paintEvent
    ///     Overridden method called when the widget needs to be repainted.
    /// \param event - A QPaintEvent parameter representing the paint event.
    ///
    void paintEvent(QPaintEvent *event) override;

private:
    ///
    /// \brief ui
    /// UI for the Quiz.
    ///
    Ui::Quiz *ui;

    /*
     * Below are objects regarding the quiz popup window.
     */
    QString randomQuestion;
    QList<int> numbers;
    QList<QString> questions;
    QMap<QString, QList<QString>> questionBank;
    int quesIndex = 0, correct = 2;

    ///
    /// \brief handleOptionButtonClick
    ///     Helper method for clicking buttons.
    /// \param button - The button which is clicked by user.
    ///
    void handleOptionButtonClick(QPushButton *button);

    ///
    /// \brief disableOptionButtons
    /// Disables the option buttons, typically used to prevent user interaction during certain game events.
    ///
    void disableOptionButtons();

    ///
    /// \brief generateConfettiColors
    /// Generates colors for confetti particles, ensuring a diverse and visually appealing appearance.
    ///
    void generateConfettiColors();

    ///
    /// \brief createConfetti
    /// Creates and initializes confetti particles for a celebratory effect.
    ///
    void createConfetti();

    ///
    /// \brief createGround
    ///     Creates a ground object with specified dimensions.
    /// \param neg - The top side.
    /// \param pos - The bottom side.
    ///
    void createGround(float neg, float pos);

    ///
    /// \brief updateWorld
    /// Updates the confetti painting.
    ///
    void updateWorld();

    ///
    /// \brief randomizeSelection
    ///     Randomizes the selection order based on the provided list of numbers.
    /// \param numbers - A QList of integers representing the options to be randomized.
    ///
    void randomizeSelection(QList<int> numbers);

    QTimer timer;

    /*
     * Below are confetti effect related objects.
     */
    b2World *top;
    b2World *bottom;
    QVector<QColor> confettiColors;
    QList<b2Body*> confettiPieces;
};

#endif // QUIZ_H
